name: Swordofmagic7
version: '${project.version}'
main: swordofmagic7.SomCore
api-version: 1.18
authors: [ MomiNeko ]
description: Swordofmagic7
depend: [ HolographicDisplays, Citizens, LibsDisguises, ProtocolLib ]

commands:
  getItem:
    permission: som7.developer
    description: description
    usage: /<command>
  getRune:
    permission: som7.developer
    description: description
    usage: /<command>
  getExp:
    permission: som7.developer
    description: description
    usage: /<command>
  getLevel:
    permission: som7.developer
    description: description
    usage: /<command>
  getClassExp:
    permission: som7.developer
    description: description
    usage: /<command>
  getEffect:
    permission: som7.developer
    description: description
    usage: /<command>
  mobSpawn:
    aliases: ms
    permission: som7.developer
    description: description
    usage: /<command>
  save:
    permission: som7.developer
    description: description
    usage: /<command>
  load:
    permission: som7.developer
    description: description
    usage: /<command>
  bukkitTasks:
    permission: som7.developer
    description: description
    usage: /<command>
  loadedPlayer:
    permission: som7.developer
    description: description
    usage: /<command>
  SomReload:
    permission: som7.developer
    description: description
    usage: /<command>
  test:
    permission: som7.developer
    description: description
    usage: /<command>
  itemDataEdit:
    permission: som7.developer
    description: description
    usage: /<command>
  mobSpawnerDataEdit:
    permission: som7.developer
    description: description
    usage: /<command>
  mobSpawnerDataCreate:
    permission: som7.developer
    description: description
    usage: /<command>
  defenseBattleStartWave:
    permission: som7.developer
    description: description
    usage: /<command>
  defenseBattleEndWave:
    permission: som7.developer
    description: description
    usage: /<command>
  sendData:
    permission: som7.developer
    description: description
    usage: /<command>
  classSelect:
    permission: som7.developer
    description: description
    usage: /<command>
  skillCTReset:
    permission: som7.developer
    description: description
    usage: /<command>
  setNick:
    permission: som7.developer
    description: description
    usage: /<command>

  gm:
    permission: som7.builder
    description: description
    usage: /<command> 1|2|3
  flySpeed:
    aliases: fs
    permission: som7.builder
    description: description
    usage: /<command>
  playMode:
    aliases: pm
    permission: som7.builder
    description: description
    usage: /<command>

  dataReload:
    permission: som7.data.reload
    description: description
    usage: /<command>
  titleReload:
    aliases: tr
    permission: som7.title.editor
    description: description
    usage: /<command>

  menu:
    description: description
    usage: /<command>
  m:
    description: description
    usage: /<command>
  skill:
    aliases: s
    description: description
    usage: /<command>
  attribute:
    aliases: [attr, a]
    description: description
    usage: /<command>
  damageLog:
    description: description
    usage: /<command>
  expLog:
    description: description
    usage: /<command>
  dropLog:
    description: description
    usage: /<command>
  pvpMode:
    description: description
    usage: /<command>
  strafeMode:
    description: description
    usage: /<command>
  castMode:
    description: description
    usage: /<command>
  effectLog:
    description: description
    usage: /<command>
  viewFormat:
    description: description
    usage: /<command>
  spawn:
    description: description
    usage: /<command>
  playerInfo:
    aliases: [info, i]
    description: description
    usage: /<command>
  tickTime:
    description: description
    usage: /<command>
  reqExp:
    description: description
    usage: /<command>
  reqExpAll:
    description: description
    usage: /<command>
  taggame:
    description: description
    usage: /<command>
  party:
    aliases: pt
    description: description
    usage: /<command>
  itemInventorySort:
    aliases: iis
    description: description
    usage: /<command>
  runeInventorySort:
    aliases: ris
    description: description
    usage: /<command>
  petInventorySort:
    aliases: pis
    description: description
    usage: /<command>
  itemInventorySortReverse:
    aliases: iisr
    description: description
    usage: /<command>
  runeInventorySortReverse:
    aliases: risr
    description: description
    usage: /<command>
  petInventorySortReverse:
    aliases: pisr
    description: description
    usage: /<command>
  tutorial:
    description: description
    usage: /<command>
  trade:
    description: description
    usage: /<command>
  textView:
    description: description
    usage: /<command>
  uuid:
    description: description
    usage: /<command>
  effectInfo:
    aliases: ei
    description: description
    usage: /<command>
  sideBarToDo:
    aliases: sbtd
    description: description
    usage: /<command>
  fishingDisplayNum:
    aliases: fdn
    description: description
    usage: /<command>
  fishingUseCombo:
    aliases: fuc
    description: description
    usage: /<command>
  setTitle:
    description: description
    usage: /<command>
  HoloSelfView:
    aliases: hsv
    description: description
    usage: /<command>
  checkTitle:
    description: description
    usage: /<command>
  reqlifeExp:
    description: description
    usage: /<command>
  reqlifeExpAll:
    description: description
    usage: /<command>
  auction:
    aliases: auc
    description: description
    usage: /<command>
  market:
    description: description
    usage: /<command>
  setFishingCombo:
    description: description
    usage: /<command>
  mobInfo:
    aliases: mi
    description: description
    usage: /<command>
  serverInfo:
    aliases: si
    description: description
    usage: /<command>
  itemInfo:
    aliases: ii
    description: description
    usage: /<command>
  runeInfo:
    aliases: ri
    description: description
    usage: /<command>
  ch:
    aliases: channel
    description: description
    usage: /<command>
  nickReset:
    description: description
    usage: /<command>
  skillSlot:
    aliases: ss
    description: description
    usage: /<command>
  runeFilter:
    aliases: rf
    description: description
    usage: /<command>
  entities:
    description: description
    usage: /<command>
  loadOnLiveServer:
    description: description
    usage: /<command>
  setFastUpgrade:
    description: description
    usage: /<command>
  cast:
    description: description
    usage: /<command>
  itemSearch:
    aliases: is
    description: description
    usage: /<command>
  runeSearch:
    aliases: rs
    description: description
    usage: /<command>
  petSearch:
    aliases: ps
    description: description
    usage: /<command>