name: Swordofmagic7
version: '${project.version}'
main: swordofmagic7.System
api-version: 1.18
authors: [ MomiNeko ]
description: Swordofmagic7
softdepend: [ HolographicDisplays, Citizens, LibsDisguises ]

commands:
  gm:
    permission: debug.som7
    description: description
    usage: /<command> 1|2|3
  get:
    permission: debug.som7
    description: description
    usage: /<command>
  getRune:
    permission: debug.som7
    description: description
    usage: /<command>
  getExp:
    permission: debug.som7
    description: description
    usage: /<command>
  getLevel:
    permission: debug.som7
    description: description
    usage: /<command>
  getClassExp:
    permission: debug.som7
    description: description
    usage: /<command>
  getClassLevel:
    permission: debug.som7
    description: description
    usage: /<command>
  getEffect:
    permission: debug.som7
    description: description
    usage: /<command>
  mobSpawn:
    aliases: ms
    permission: debug.som7
    description: description
    usage: /<command>
  playMode:
    aliases: pm
    permission: debug.som7
    description: description
    usage: /<command>
  save:
    permission: debug.som7
    description: description
    usage: /<command>
  load:
    permission: debug.som7
    description: description
    usage: /<command>
  flySpeed:
    aliases: fs
    permission: debug.som7
    description: description
    usage: /<command>
  bukkitTasks:
    permission: debug.som7
    description: description
    usage: /<command>
  loadedPlayer:
    permission: debug.som7
    description: description
    usage: /<command>
  SomReload:
    permission: debug.som7
    description: description
    usage: /<command>
  test:
    permission: debug.som7
    description: description
    usage: /<command>
  setItemEquipmentStatusMultiply:
    permission: debug.som7
    description: description
    usage: /<command>

  menu:
    description: description
    usage: /<command>
  m:
    description: description
    usage: /<command>
  skill:
    aliases: s
    description: description
    usage: /<command>
  attribute:
    aliases: [attr, a]
    description: description
    usage: /<command>
  damageLog:
    description: description
    usage: /<command>
  expLog:
    description: description
    usage: /<command>
  dropLog:
    description: description
    usage: /<command>
  pvpMode:
    description: description
    usage: /<command>
  strafeMode:
    description: description
    usage: /<command>
  castMode:
    description: description
    usage: /<command>
  viewFormat:
    description: description
    usage: /<command>
  spawn:
    description: description
    usage: /<command>
  info:
    aliases: i
    description: description
    usage: /<command>
  tickTime:
    description: description
    usage: /<command>
  reqExp:
    description: description
    usage: /<command>
  taggame:
    description: description
    usage: /<command>
  party:
    aliases: pt
    description: description
    usage: /<command>
  itemInventorySort:
    aliases: iis
    description: description
    usage: /<command>
  runeInventorySort:
    aliases: ris
    description: description
    usage: /<command>
  petInventorySort:
    aliases: pis
    description: description
    usage: /<command>
  itemInventorySortReverse:
    aliases: iisr
    description: description
    usage: /<command>
  runeInventorySortReverse:
    aliases: risr
    description: description
    usage: /<command>
  petInventorySortReverse:
    aliases: pisr
    description: description
    usage: /<command>
  tutorial:
    description: description
    usage: /<command>
  trade:
    description: description
    usage: /<command>
  textView:
    description: description
    usage: /<command>
  uuid:
    description: description
    usage: /<command>
  effectInfo:
    aliases: efInfo
    description: description
    usage: /<command>
  sideBarToDo:
    aliases: sbtd
    description: description
    usage: /<command>