name: Swordofmagic7
version: '${project.version}'
main: swordofmagic7.System
api-version: 1.18
authors: [ MomiNeko ]
description: Swordofmagic7
softdepend: [ HolographicDisplays ]

commands:
  gm:
    permission: debug.som7
    description: description
    usage: /<command> 1|2|3
  get:
    permission: debug.som7
    description: description
    usage: /<command>
  mobSpawn:
    aliases: ms
    permission: debug.som7
    description: description
    usage: /<command>
  playMode:
    permission: debug.som7
    description: description
    usage: /<command>
  save:
    permission: debug.som7
    description: description
    usage: /<command>
  load:
    permission: debug.som7
    description: description
    usage: /<command>
  flySpeed:
    permission: debug.som7
    description: description
    usage: /<command>
  test:
    permission: debug.som7
    description: description
    usage: /<command>

  menu:
    description: description
    usage: /<command>
  m:
    description: description
    usage: /<command>
  skill:
    aliases: s
    description: description
    usage: /<command>
  attribute:
    aliases: [attr, a]
    description: description
    usage: /<command>
  damageLog:
    description: description
    usage: /<command>
  expLog:
    description: description
    usage: /<command>
  dropLog:
    description: description
    usage: /<command>
  pvpMode:
    description: description
    usage: /<command>
  strafeMode:
    description: description
    usage: /<command>
  castMode:
    description: description
    usage: /<command>
  viewFormat:
    description: description
    usage: /<command>
  spawn:
    description: description
    usage: /<command>
  info:
    aliases: i
    description: description
    usage: /<command>
  tickTime:
    description: description
    usage: /<command>
  reqExp:
    description: description
    usage: /<command>
  taggame:
    description: description
    usage: /<command>