[versions]
kotlin = "2.1.0-RC2"
shadow = "8.3.5"
pluginYml = "0.6.0"

paperApi = "1.21.3-R0.1-SNAPSHOT"
protocolLib = "5.1.0"
libsDisguises = "10.0.44"
nuVotifier = "2.7.2"
kotlinSerializationJson = "1.7.3"
decentHolograms = "2.8.12"
citizens = "2.0.35-SNAPSHOT"
itemNbtApi = "2.14.0"
jedis = "5.2.0"

[plugins]
kotlin =  { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
pluginYml = { id = "net.minecrell.plugin-yml.bukkit", version.ref = "pluginYml" }

[libraries]
paperApi = { group = "io.papermc.paper", name = "paper-api", version.ref = "paperApi" }
protocolLib = { group = "com.comphenix.protocol", name = "ProtocolLib", version.ref = "protocolLib" }
libsDisguises = { group = "LibsDisguises", name = "LibsDisguises", version.ref = "libsDisguises" }
nuVotifier = { group = "com.github.NuVotifier", name = "NuVotifier", version.ref = "nuVotifier" }
kotlinSerializationJson = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinSerializationJson" }
decentHolograms = { group = "com.github.decentsoftware-eu", name = "decentholograms", version.ref = "decentHolograms" }
citizens = { group = "net.citizensnpcs", name = "citizens-main", version.ref = "citizens" }
itemNbtApi = { group = "de.tr7zw", name = "item-nbt-api", version.ref = "itemNbtApi" }
jedis = { group = "redis.clients", name = "jedis", version.ref = "jedis" }